In [34]:
import pandas as pd

In [35]:
batsman = pd.read_csv('../dataset/IPL_BATSMAN.csv')
bowlers = pd.read_csv('../dataset/IPL_BOWLERS.csv')

In [36]:
batsman.head(5)

,PLAYER_ID,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM,TOTAL_RUNS,BATTING_AVG,30+RUNS,50+RUNS,70+RUNS,S/R_vs_SPIN,...,DOT_BALLS_%,BALLS_FACED,CATCHES_TAKEN,CATCHES_DROPPED,RUN_OUT_(%),RUNS_SAVED,BOUNDARIES_SAVED,CAUGHT_BEHIND,STUMPING,RUN_OUTS
0,c6182645-54c7-4535-9012-895e2dd841eb_IPL,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,c6182645-54c7-4535-9012-895e2dd841eb_T20I,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,c6182645-54c7-4535-9012-895e2dd841eb_ODI,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,c6182645-54c7-4535-9012-895e2dd841eb_STATE_T20,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,c6182645-54c7-4535-9012-895e2dd841eb_SMAT_ELITE,KL Rahul,WK-Batter,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
bowlers.head(5)

,PLAYER_ID,PLAYER_NAME,PLAYER_TYPE,PLAYER_IPL_TEAM,TOTAL_WICKETS,BOWLING_AVG,ECONOMY_RATE,2WK_HAULS,3WK_HAULS,4WK_HAULS,...,TOTAL_DOTS,BEST_FIGURE,STRIKE_RATE,MAIDENS,PP/DEATH_FIG,CATCHES_TAKEN,CATCHES_DROPPED,RUN_OUT_(%),RUNS_SAVED,BOUNDARIES_SAVED
0,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_IPL,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_T20I,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_ODI,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_STATE_T20,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,36e9ecc2-0b2e-4108-9dac-ab53bfe2423a_SMAT_ELITE,Mitchell Starc,Bowler,DC,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
set(batsman['PLAYER_IPL_TEAM'])

{'CSK', 'DC', 'GT', 'KKR', 'LSG', 'MI', 'PK', 'RCB', 'RR', 'SRH'}

#### Splitting Dataset template between Nikhil, atharva and Gaurav

(i) Nikhil Dataset

In [39]:
NIKHIL_BATSMAN_IPL = batsman[(batsman["PLAYER_IPL_TEAM"] == 'CSK' ) | (batsman["PLAYER_IPL_TEAM"] == 'GT' ) | (batsman['PLAYER_IPL_TEAM'] == 'PK') | (batsman['PLAYER_IPL_TEAM'] == 'RR')]

In [40]:
NIKHIL_BATSMAN_IPL.to_csv('../dataset/nikhil/NIKHIL_IPL_BATSMAN.csv')

In [41]:
NIKHIL_BOWLERS_IPL = bowlers[(bowlers["PLAYER_IPL_TEAM"] == 'CSK' ) | (bowlers["PLAYER_IPL_TEAM"] == 'GT' ) | (bowlers['PLAYER_IPL_TEAM'] == 'PK') | (bowlers['PLAYER_IPL_TEAM'] == 'RR')]

In [42]:
NIKHIL_BOWLERS_IPL.to_csv('../dataset/nikhil/NIKHIL_BOWLERS_IPL.csv')

(ii) Atharva Dataset

In [43]:
ATTA_BATSMAN_IPL = batsman[(batsman["PLAYER_IPL_TEAM"] == 'MI' ) | (batsman["PLAYER_IPL_TEAM"] == 'RCB' ) | (batsman['PLAYER_IPL_TEAM'] == 'KKR')]

In [44]:
ATTA_BATSMAN_IPL.to_csv('../dataset/atta/ATTA_BATSMAN_IPL.csv')

In [45]:
ATTA_BOWLERS_IPL = bowlers[(bowlers["PLAYER_IPL_TEAM"] == 'MI' ) | (bowlers["PLAYER_IPL_TEAM"] == 'RCB' ) | (bowlers['PLAYER_IPL_TEAM'] == 'KKR')]

In [46]:
ATTA_BOWLERS_IPL.to_csv('../dataset/atta/ATTA_BOWLERS_IPL.csv')

(iii) Gaurav Dataset

In [47]:
GAURAV_BATSMAN_IPL = batsman[(batsman["PLAYER_IPL_TEAM"] == 'SRH' ) | (batsman["PLAYER_IPL_TEAM"] == 'LSG' ) | (batsman['PLAYER_IPL_TEAM'] == 'DC')]

In [48]:
GAURAV_BATSMAN_IPL.to_csv('../dataset/gaurav/GAURAV_BATSMAN_IPL.csv')

In [49]:
GAURAV_BOWLERS_IPL = bowlers[(bowlers["PLAYER_IPL_TEAM"] == 'SRH' ) | (bowlers["PLAYER_IPL_TEAM"] == 'LSG' ) | (bowlers['PLAYER_IPL_TEAM'] == 'DC')]

In [50]:
GAURAV_BOWLERS_IPL.to_csv('../dataset/gaurav/GAURAV_BOWLERS_IPL.csv')